<main>
<section class="list-category">
    <ul class="menu">
                        <li>
                            <a href="index.php?page=potager">Le potager</a>
                        </li>
                        <li>
                            <a href="index.php?page=osiericulture">L'osiericulture</a>
                        </li>
                        <li>
                            <a href="index.php?page=vannerie">La vannerie</a>
                        </li>
                        <li>
                            <a href="index.php?page=fournil">Le fournil</a>
                        </li>
                        <li>
                            <a href="index.php?page=stage">Stage</a>
                        </li>
                    </ul>
</section>
</main>

