
<main>
    <div class="loading-container">
        <div class="layer-home">
            <div class="container">
                    <div class="main-title">
                        <h1>Le fournil </h1>
                        <p>Nous avons mangé du pain pendant des décennies sans effleurer l'idée de faire le notre un jour. Sous les influences croisées du hasard, de la situation géographique et des rencontres autour de chez nous, la fabrication de pain au levain naturel est devenu une habitude, transformée en activité régulière avec le construction d'un premier four à bois à l'été 2022.</p>
                    </div>
                    <article class="list-stage">
                        <h2>Nos stages disponibles</h2>
                        <?php renderHtml() ?>
    
                    </article>
                
            </div>
        </div>
    </div>
</main>