<header>
    <div class="accessibility">
        <button id="accessibility"><i class="fa-solid fa-eye-low-vision"></i></button>
    </div>
    <nav>

        <div class="logo-img">
            <a href="index.php"><img alt="chien-roni" class="little-roni" src="./image/logo/roni.png" /></a>
        </div>
        <input type="checkbox" id="check">
        <label for="check" class="hamburger-btn"> <i class="fa-solid fa-bars"></i></label>

        <div class="nav-links">
            <ul>
                <li>
                    <a class="active" href="index.php?page=home">Accueil</a>
                </li>
                <div class="hover">
                <li>
                    
                    <a class="padding" href="index.php?page=activites">Nos activités <i class="fa-solid fa-angle-down"></i></a>
                    <ul class="sub-menu">
                        
                        <li>
                            <a href="index.php?page=potager">Le potager</a>
                        </li>
                        <li>
                            <a href="index.php?page=osiericulture">L'osiericulture</a>
                        </li>
                        <li>
                            <a href="index.php?page=vannerie">La vannerie</a>
                        </li>
                        <li>
                            <a href="index.php?page=fournil">Le fournil</a>
                        </li>
                        <li>
                            <a href="index.php?page=stage">Stage</a>
                        </li>
                        
                    </ul>
                </li>
                </div>
                <li><a href="index.php?page=vegetables">Que manger ?</a></li>
                <li><a href="index.php?page=contact">Contact</a></li>
                <?php
                if (empty($_SESSION['user'])) { ?>

                    <li>
                        <a href="index.php?page=connection">Se connecter</a>
                    </li>
                    <li>
                        <a href="index.php?page=inscription">S'inscrire</a>
                    </li>
                <?php } else { ?>
                    <li>
                        <a href="index.php?page=connected">Mon profil</a>
                    </li>
                <?php }
                if (isset($_SESSION['role'])) { ?>
                    <li>
                        <a href="index.php?page=admin">Back-office</a>
                    </li>
                <?php } ?>




            </ul>

        </div>
    </nav>
</header>