<main>
<div class="loading-container">
    <div class="layer-home">
        <div class="container">
            <section class="animate-area">
                <p>Ici, et avec nous, tu peux apprendre</p>
                <p class="animate-text">
                    <span>à jardiner.</span>
                    <span>l'art du pain.</span>
                    <span>l'osiériculture.</span>
                    <span>la vannerie.</span>
                </p>
            </section>
            
            <section class="main-title bg">
                <h1>La ferme du gros chataigner</h1>
               
                <p>Le gros châtaignier est un project de vie protéiforme, se déroulant sur un peu moins de deux hectares, dans le bocage des deux sèvres, sur la commune de la Chapelle Saint Etienne.</p>
            </section>
            
            <section>
                <div class="carousel" data-carousel>
                    <button class="carousel-button left-button" data-carousel-button="prev">&#8249;</button>
                    <button class="carousel-button right-button" data-carousel-button="next">&#8250;</button>
                <ul data-slides>
                    <li class="slide" data-active>
                        <img src="./image/img1.jpg" alt="semi" />
                    </li>
                    <li class="slide">
                        <img src="./image/img2.jpg" alt="legumes"/>
                    </li>
                    <li class="slide">
                        <img src="./image/img3.jpg" alt="serre"/>
                    </li>
                </ul>
                </div>
            </section>
        </div>
    </div>
</div>
</main>

<script  src="./js/carroussel.js" defer></script>

<script  src="./js/textanim.js" defer></script>

