<main>
<div class="loading-container">
    <video id="video1" preload="" autoplay="" muted="" playsinline="" loop="">
    <source src="./image/video/productionID_4401518.mp4" type="video/mp4">
    </video> 
    <div class="layer">
        <div class="text-loading-container">
            <h1 class="title-loading">La ferme du gros chataigner</h1>
        </div>
        <div class="img-container">
        <a href="index.php?page=home"><img alt="chien-roni" class="roni" src="./image/logo/roni.png"/></a>
        </div>
        
    </div>
</div>
</main>

 <script src="./js/texttranslate.js"></script>