<main>
    <div class="loading-container">
        <div class="layer-home">
            <div class="container">
                    <div class="main-title">
                        <h1>L'osiericulture </h1>
                        <p>L'oseraie du gros châtaignier, plantée à l'hiver 2022, est riche de plus d'une dizaine de variétés d'osier. On y trouve notamment le fameux noir de Vilaine (salix triandra), l'osier des Vignes (Salix Alba Vittelina), l'osier des Vanniers (Salix Vinimalis), l'osier Sainte Reine Rouge (Salix Fragilis).
                            Située tout à l'extérieur, proche d'un très gros châtaignier, cet oseraie est le dernier maillon de notre chaine avant la forêt, et nos amis cervidés l'ont prise en affection. On récolte les branches de l'année en début d'hiver, pour ouvrager tout types de vannerie.</p>
                    </div>
                    <article class="list-stage">
                    <h2>Nos stages disponibles</h2>
                    <?php renderHtml() ?>
                    </article>
            </div>
        </div>
    </div>
</main>
