<main>
    <div class="loading-container">
        <div class="layer-home">
            <div class="container">
                    <section class="main-title">
                        <h1>Le potager </h1>
                        <p>Le potager du gros châtaignier est à la fois un projet vivrier et un ensemble d'expérimentations culturales. Il s'agit d'obtenir un ensemble de productions maraichères classiques (légumes, légumineuses, fruits, petits fruits...) en cherchant toujours les méthodes les plus efficaces, les plus résiliantes et les moins pertubatrices pour le milieu naturel. Nous utilisons un ensemble de techniques culturales issues du MSV (maraichage sur sol vivant), et les produits phytosanitaires sont évidemments proscrits. Les mêmes principes de culture et d'expérimentation sont appliquées à la petite parcelle viticole (500m² de Chenin et 500m² de Chardonnay), en place depuis 2023. Les arbres sont introduits au sein du vignoble, servant de supports pour la croissance de la vigne, suivant une technique ancienne, encore utilsiée dans certaines régions méditéranéennes, la vita maritatta (la vigne mariée).</p>
                    </section>
                    <article class="list-stage">
                        <h2>Nos stages disponibles</h2>
                        <?php renderHtml() ?>
    
                    </article>
    
            </div>
        </div>
    </div>
</main>
