<main>
    <div class="loading-container">
        <div class="layer-home">
            <div class="container">
                <div class="main-title">
                    <h1>Les stages </h1>
                    <p>L'ensemble des compétences et des expérimentations développées au gros châtaignier sont destinées à être transmises et partagées. Des stages de tout type et de toutes durées sont régulièrement mis en place, il ne faut pas hésiter à nous contacter pour plus de détails.</p>
                </div>
            </div>
        </div>
    </div>
</main>

