<main>
    <div class="loading-container">
        <div class="layer-home">
            <div class="container">
                    <div class="main-title">
                        <h1>La vannerie </h1>
                        <p>La Vannerie est une technologie ancienne, un art, un artisannat. Il s'agit de transformer les jeunes pousses d'osier issues du saule en une farandole de paniers, abats-jours et autres objets d'artisanat. La vannerie dite sauvage est aussi un lien fort avec le paysage : on utilise la diversité végétale locale (clématite, ronce, molinie...) que l'on se contente de cueillir sans avoir à la cultiver.
                            La vannerie recouvre un ensemble de techniques très diverses : vannerie sur arceaux, vannerie à montants parallèles, vannerie spiralée cousue.</p>
                    </div>
                    <article class="list-stage">
                        <h2>Nos stages disponibles</h2>
                        <?php renderHtml() ?>
                    </article>
            </div>
        </div>
    </div>
</main>
